sudo: required
services:
  - docker

before_install:
  - docker build -t ibrahimBelkhiria/react-test -f ./client/Dockerfile.dev

script:
  - docker run ibrahimBelkhiria/react-test npm test -- --coverage

after_success:
  - docker build -t ibrahimBelkhiria/multi-client ./client
  - docker build -t ibrahimBelkhiria/multi-nginx ./nginx
  - docker build -t ibrahimBelkhiria/multi-server ./server
  - docker build -t ibrahimBelkhiria/multi-worker ./worker
   # login to docker cli 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub 
  - docker push  ibrahimBelkhiria/multi-client 
  - docker push  ibrahimBelkhiria/multi-nginx 
  - docker push  ibrahimBelkhiria/multi-server 
  - docker push  ibrahimBelkhiria/multi-worker 